ports:
- port: 1234
  onOpen: ignore
- port: 1235
  onOpen: ignore
- port: 1236
  onOpen: ignore
tasks:
- command: |
    export BROWSER="$(pwd)/.gitpod-preview.sh"
    if [ -e "$EXAMPLE/yarn.lock" ]
    then
      cd $EXAMPLE
      [ -e README.md ] && gp open README.md
      yarn
      yarn watch
    else
      echo ""
      echo "Hello. Thank you for looking at the Tensorflow-JS Examples."
      echo ""
      echo "To try an an example, do"
      echo "1. cd to the directory of the example"
      echo "2. run the example, as it is specified in the readme"
    fi
