const express = require('express');
const app = express();
const cors = require('cors')

app.use(cors())

app.listen(8000, () => {
  console.log('Server listening on port 8000.');
});

app.route('/api/merch/:category').get((req, res) => {
  const category = req.params.category ?? 'all';
  res.send(Merch.filter(merch => category === 'all' ? true : merch.category.startsWith(category)));
});

interface Merch {
  item_name: string;
  item_id: string;
  price: string;
  item_category: string;
  index: number;
  name: string;
  id: string;
  category: string;
  position: string;
}

const Merch: Merch[] = [
  {
    item_name: 'Google Toddler FC Zip Hoodie',
    item_id: 'GGOEGXXX1136',
    price: '35.00',
    item_category: 'apparel-kids',
    index: 1,
    name: 'Google Toddler FC Zip Hoodie',
    id: 'GGOEGXXX1136',
    category: 'apparel-kids',
    position: '1',
  },
  {
    item_name: 'Google Youth FC Zip Hoodie',
    item_id: 'GGOEGXXX1137',
    price: '45.00',
    item_category: 'apparel-kids',
    index: 2,
    name: 'Google Youth FC Zip Hoodie',
    id: 'GGOEGXXX1137',
    category: 'apparel-kids',
    position: '2',
  },
  {
    item_name: 'Android Pocket Youth Tee Green',
    item_id: 'GGOEAXXX1302',
    price: '25.00',
    item_category: 'apparel-kids',
    index: 3,
    name: 'Android Pocket Youth Tee Green',
    id: 'GGOEAXXX1302',
    category: 'apparel-kids',
    position: '3',
  },
  {
    item_name: 'Google Youth Hero Tee Grey',
    item_id: 'GGOEGXXX1360',
    price: '24.00',
    item_category: 'apparel-kids',
    index: 4,
    name: 'Google Youth Hero Tee Grey',
    id: 'GGOEGXXX1360',
    category: 'apparel-kids',
    position: '4',
  },
  {
    item_name: 'Google Toddler Tee White',
    item_id: 'GGOEGXXX1346',
    price: '24.00',
    item_category: 'apparel-kids',
    index: 5,
    name: 'Google Toddler Tee White',
    id: 'GGOEGXXX1346',
    category: 'apparel-kids',
    position: '5',
  },
  {
    item_name: 'Google Youth FC Longsleeve Charcoal',
    item_id: 'GGOEGXXX1131',
    price: '30.00',
    item_category: 'apparel-kids',
    index: 6,
    name: 'Google Youth FC Longsleeve Charcoal',
    id: 'GGOEGXXX1131',
    category: 'apparel-kids',
    position: '6',
  },
  {
    item_name: 'Google Toddler Hero Tee Olive',
    item_id: 'GGOEGXXX1357',
    price: '24.00',
    item_category: 'apparel-kids',
    index: 7,
    name: 'Google Toddler Hero Tee Olive',
    id: 'GGOEGXXX1357',
    category: 'apparel-kids',
    position: '7',
  },
  {
    item_name: 'Google Youth F/C Pullover Hoodie',
    item_id: 'GGOEGXXX1167',
    price: '40.00',
    item_category: 'apparel-kids',
    index: 8,
    name: 'Google Youth F/C Pullover Hoodie',
    id: 'GGOEGXXX1167',
    category: 'apparel-kids',
    position: '8',
  },
  {
    item_name: 'Google Youth Hero Tee Maroon',
    item_id: 'GGOEGXXX1361',
    price: '24.00',
    item_category: 'apparel-kids',
    index: 9,
    name: 'Google Youth Hero Tee Maroon',
    id: 'GGOEGXXX1361',
    category: 'apparel-kids',
    position: '9',
  },
  {
    item_name: 'Google Kids Playful Tee',
    item_id: 'GGOEGXXX1183',
    price: '25.00',
    item_category: 'apparel-kids',
    index: 10,
    name: 'Google Kids Playful Tee',
    id: 'GGOEGXXX1183',
    category: 'apparel-kids',
    position: '10',
  },
  {
    item_name: 'Android Pocket Toddler Tee White',
    item_id: 'GGOEAXXX1298',
    price: '23.00',
    item_category: 'apparel-kids',
    index: 11,
    name: 'Android Pocket Toddler Tee White',
    id: 'GGOEAXXX1298',
    category: 'apparel-kids',
    position: '11',
  },
  {
    item_name: 'Android Pocket Onesie White',
    item_id: 'GGOEAXXX1300',
    price: '22.00',
    item_category: 'apparel-kids',
    index: 12,
    name: 'Android Pocket Onesie White',
    id: 'GGOEAXXX1300',
    category: 'apparel-kids',
    position: '12',
  },
  {
    item_name: 'Google Eco Tee Black',
    item_id: 'GGOEGXXX1189',
    price: '22.00',
    item_category: 'apparel-unisex',
    index: 1,
    name: 'Google Eco Tee Black',
    id: 'GGOEGXXX1189',
    category: 'apparel-unisex',
    position: '1',
  },
  {
    item_name: 'Super G Unisex Joggers',
    item_id: 'GGOEGXXX1613',
    price: '37.00',
    item_category: 'apparel-unisex',
    index: 2,
    name: 'Super G Unisex Joggers',
    id: 'GGOEGXXX1613',
    category: 'apparel-unisex',
    position: '2',
  },
  {
    item_name: 'Google Charcoal Unisex Badge Tee',
    item_id: 'GGOEGXXX1633',
    price: '21.00',
    item_category: 'apparel-unisex',
    index: 3,
    name: 'Google Charcoal Unisex Badge Tee',
    id: 'GGOEGXXX1633',
    category: 'apparel-unisex',
    position: '3',
  },
  {
    item_name: '#IamRemarkable Unisex T-Shirt',
    item_id: 'GGCOGXXX1006',
    price: '12.00',
    item_category: 'apparel-unisex',
    index: 4,
    name: '#IamRemarkable Unisex T-Shirt',
    id: 'GGCOGXXX1006',
    category: 'apparel-unisex',
    position: '4',
  },
  {
    item_name: 'Google Zip Hoodie F/C',
    item_id: 'GGOEGXXX1109',
    price: '60.00',
    item_category: 'apparel-unisex',
    index: 5,
    name: 'Google Zip Hoodie F/C',
    id: 'GGOEGXXX1109',
    category: 'apparel-unisex',
    position: '5',
  },
  {
    item_name: 'Google Sherpa Zip Hoodie Navy',
    item_id: 'GGOEGXXX1347',
    price: '69.00',
    item_category: 'apparel-unisex',
    index: 6,
    name: 'Google Sherpa Zip Hoodie Navy',
    id: 'GGOEGXXX1347',
    category: 'apparel-unisex',
    position: '6',
  },
  {
    item_name: 'Google Cloud Unisex Tee',
    item_id: 'GGOECXXX1636',
    price: '28.00',
    item_category: 'apparel-unisex',
    index: 7,
    name: 'Google Cloud Unisex Tee',
    id: 'GGOECXXX1636',
    category: 'apparel-unisex',
    position: '7',
  },
  {
    item_name: 'Google Land & Sea Unisex Tee',
    item_id: 'GGCOGXXX1569',
    price: '25.00',
    item_category: 'apparel-unisex',
    index: 8,
    name: 'Google Land & Sea Unisex Tee',
    id: 'GGCOGXXX1569',
    category: 'apparel-unisex',
    position: '8',
  },
  {
    item_name: 'Google Crew Socks',
    item_id: 'GGOEGAEB105210',
    price: '16.00',
    item_category: 'apparel-socks',
    index: 9,
    name: 'Google Crew Socks',
    id: 'GGOEGAEB105210',
    category: 'apparel-socks',
    position: '9',
  },
  {
    item_name: 'Google Navy Speckled Tee',
    item_id: 'GGOEGXXX1344',
    price: '30.00',
    item_category: 'apparel-unisex',
    index: 10,
    name: 'Google Navy Speckled Tee',
    id: 'GGOEGXXX1344',
    category: 'apparel-unisex',
    position: '10',
  },
  {
    item_name: 'Google Crewneck Sweatshirt Green',
    item_id: 'GGOEGXXX1342',
    price: '55.00',
    item_category: 'apparel-unisex',
    index: 11,
    name: 'Google Crewneck Sweatshirt Green',
    id: 'GGOEGXXX1342',
    category: 'apparel-unisex',
    position: '11',
  },
  {
    item_name: 'Google F/C Long Sleeve Tee Charcoal',
    item_id: 'GGOEGXXX1038',
    price: '30.00',
    item_category: 'apparel-unisex',
    index: 12,
    name: 'Google F/C Long Sleeve Tee Charcoal',
    id: 'GGOEGXXX1038',
    category: 'apparel-unisex',
    position: '12',
  },
  {
    item_name: 'YouTube Twill Sandwich Cap Black',
    item_id: 'GGOEYHBB102199',
    price: '13.00',
    item_category: 'apparel-headgear',
    index: 1,
    name: 'YouTube Twill Sandwich Cap Black',
    id: 'GGOEYHBB102199',
    category: 'apparel-headgear',
    position: '1',
  },
  {
    item_name: 'Google Leather Strap Hat Black',
    item_id: 'GGOEGHPB120910',
    price: '17.00',
    item_category: 'apparel-headgear',
    index: 2,
    name: 'Google Leather Strap Hat Black',
    id: 'GGOEGHPB120910',
    category: 'apparel-headgear',
    position: '2',
  },
  {
    item_name: 'YouTube Leather Strap Hat Black',
    item_id: 'GGOEYHPB121110',
    price: '17.00',
    item_category: 'apparel-headgear',
    index: 3,
    name: 'YouTube Leather Strap Hat Black',
    id: 'GGOEYHPB121110',
    category: 'apparel-headgear',
    position: '3',
  },
  {
    item_name: 'Google Speckled Beanie Grey',
    item_id: 'GGOEGAEJ135510',
    price: '20.00',
    item_category: 'apparel-headgear',
    index: 4,
    name: 'Google Speckled Beanie Grey',
    id: 'GGOEGAEJ135510',
    category: 'apparel-headgear',
    position: '4',
  },
  {
    item_name: 'Android Iconic Beanie',
    item_id: 'GGOEAHPJ131210',
    price: '10.00',
    item_category: 'apparel-headgear',
    index: 5,
    name: 'Android Iconic Beanie',
    id: 'GGOEAHPJ131210',
    category: 'apparel-headgear',
    position: '5',
  },
  {
    item_name: 'Android Iconic Hat Green',
    item_id: 'GGOEAHPL130910',
    price: '16.00',
    item_category: 'apparel-headgear',
    index: 6,
    name: 'Android Iconic Hat Green',
    id: 'GGOEAHPL130910',
    category: 'apparel-headgear',
    position: '6',
  },
  {
    item_name: 'Android Iconic Hat White',
    item_id: 'GGOEAHPL131010',
    price: '16.00',
    item_category: 'apparel-headgear',
    index: 7,
    name: 'Android Iconic Hat White',
    id: 'GGOEAHPL131010',
    category: 'apparel-headgear',
    position: '7',
  },
  {
    item_name: 'Google Bear Baby Blanket Beige',
    item_id: 'GGCOGCBD162999',
    price: '24.00',
    item_category: 'new',
    index: 1,
    name: 'Google Bear Baby Blanket Beige',
    id: 'GGCOGCBD162999',
    category: 'new',
    position: '1',
  },
  {
    item_name: 'Google Bot (Multicolored)',
    item_id: 'GGOEGEBA164399',
    price: '10.00',
    item_category: 'new',
    index: 2,
    name: 'Google Bot (Multicolored)',
    id: 'GGOEGEBA164399',
    category: 'new',
    position: '2',
  },
  {
    item_name: 'Google Cloud Journal',
    item_id: 'GGOECOLJ164299',
    price: '18.00',
    item_category: 'new',
    index: 3,
    name: 'Google Cloud Journal',
    id: 'GGOECOLJ164299',
    category: 'new',
    position: '3',
  },
  {
    item_name: 'White Google Cloud Tumbler',
    item_id: 'GGOECDNQ163899',
    price: '27.00',
    item_category: 'new',
    index: 4,
    name: 'White Google Cloud Tumbler',
    id: 'GGOECDNQ163899',
    category: 'new',
    position: '4',
  },
  {
    item_name: 'Google Shoreline Water Bottle',
    item_id: 'GGOECDHQ163999',
    price: '26.00',
    item_category: 'new',
    index: 5,
    name: 'Google Shoreline Water Bottle',
    id: 'GGOECDHQ163999',
    category: 'new',
    position: '5',
  },
  {
    item_name: 'Google Cloud Pen',
    item_id: 'GGOECOAQ163799',
    price: '3.00',
    item_category: 'new',
    index: 6,
    name: 'Google Cloud Pen',
    id: 'GGOECOAQ163799',
    category: 'new',
    position: '6',
  },
  {
    item_name: 'Google Chrome Dino Light Up Water Bottle',
    item_id: 'GGOEGDHB163199',
    price: '24.00',
    item_category: 'new',
    index: 7,
    name: 'Google Chrome Dino Light Up Water Bottle',
    id: 'GGOEGDHB163199',
    category: 'new',
    position: '7',
  },
  {
    item_name: 'Google Navy Polo',
    item_id: 'GGOEGXXX1632',
    price: '48.00',
    item_category: 'new',
    index: 8,
    name: 'Google Navy Polo',
    id: 'GGOEGXXX1632',
    category: 'new',
    position: '8',
  },
  {
    item_name: 'Google Charcoal Unisex Badge Tee',
    item_id: 'GGOEGXXX1633',
    price: '21.00',
    item_category: 'new',
    index: 9,
    name: 'Google Charcoal Unisex Badge Tee',
    id: 'GGOEGXXX1633',
    category: 'new',
    position: '9',
  },
  {
    item_name: 'Google Cloud Polo',
    item_id: 'GGOECXXX1635',
    price: '46.00',
    item_category: 'new',
    index: 10,
    name: 'Google Cloud Polo',
    id: 'GGOECXXX1635',
    category: 'new',
    position: '10',
  },
  {
    item_name: 'Google Cloud Unisex Tee',
    item_id: 'GGOECXXX1636',
    price: '28.00',
    item_category: 'new',
    index: 11,
    name: 'Google Cloud Unisex Tee',
    id: 'GGOECXXX1636',
    category: 'new',
    position: '11',
  },
  {
    item_name: 'Google Aluminum Bottle Red',
    item_id: 'GGOEGDHR162799',
    price: '8.00',
    item_category: 'new',
    index: 12,
    name: 'Google Aluminum Bottle Red',
    id: 'GGOEGDHR162799',
    category: 'new',
    position: '12',
  },
  {
    item_name: 'Google Land & Sea French Terry Sweatshirt',
    item_id: 'GGCOGXXX1609',
    price: '55.00',
    item_category: 'eco',
    index: 1,
    name: 'Google Land & Sea French Terry Sweatshirt',
    id: 'GGCOGXXX1609',
    category: 'eco',
    position: '1',
  },
  {
    item_name: 'Google Land & Sea Journal Set',
    item_id: 'GGCOGOCA157331',
    price: '15.00',
    item_category: 'eco',
    index: 2,
    name: 'Google Land & Sea Journal Set',
    id: 'GGCOGOCA157331',
    category: 'eco',
    position: '2',
  },
  {
    item_name: 'Google Land & Sea Nalgene Water Bottle',
    item_id: 'GGCOGDHG157299',
    price: '25.00',
    item_category: 'eco',
    index: 3,
    name: 'Google Land & Sea Nalgene Water Bottle',
    id: 'GGCOGDHG157299',
    category: 'eco',
    position: '3',
  },
  {
    item_name: "Google Land & Sea Women's Eco Tee",
    item_id: 'GGCOGXXX1570',
    price: '25.00',
    item_category: 'ecoWomens',
    index: 4,
    name: "Google Land & Sea Women's Eco Tee",
    id: 'GGCOGXXX1570',
    category: 'ecoWomens',
    position: '4',
  },
  {
    item_name: 'Android Jotter Task Pad',
    item_id: 'GGOEAOLC152099',
    price: '3.00',
    item_category: 'eco',
    index: 5,
    name: 'Android Jotter Task Pad',
    id: 'GGOEAOLC152099',
    category: 'eco',
    position: '5',
  },
  {
    item_name: 'Google Recycled Pen Black',
    item_id: 'GGOEGOAB131499',
    price: '2.00',
    item_category: 'eco',
    index: 6,
    name: 'Google Recycled Pen Black',
    id: 'GGOEGOAB131499',
    category: 'eco',
    position: '6',
  },
  {
    item_name: 'Google Recycled Pen Green',
    item_id: 'GGOEGOAH131599',
    price: '2.00',
    item_category: 'eco',
    index: 7,
    name: 'Google Recycled Pen Green',
    id: 'GGOEGOAH131599',
    category: 'eco',
    position: '7',
  },
  {
    item_name: 'Google Cotopaxi Shell',
    item_id: 'GGOEGXXX1378',
    price: '95.00',
    item_category: 'eco',
    index: 8,
    name: 'Google Cotopaxi Shell',
    id: 'GGOEGXXX1378',
    category: 'eco',
    position: '8',
  },
  {
    item_name: 'Google Black Cork Journal',
    item_id: 'GGOEGOCB131799',
    price: '12.00',
    item_category: 'eco',
    index: 9,
    name: 'Google Black Cork Journal',
    id: 'GGOEGOCB131799',
    category: 'eco',
    position: '9',
  },
  {
    item_name: 'Google KeepCup',
    item_id: 'GGOEGDHG133099',
    price: '35.00',
    item_category: 'eco',
    index: 10,
    name: 'Google KeepCup',
    id: 'GGOEGDHG133099',
    category: 'eco',
    position: '10',
  },
  {
    item_name: 'Supernatural Paper Lunch Sack',
    item_id: 'GGOEGBRD128399',
    price: '24.00',
    item_category: 'eco',
    index: 11,
    name: 'Supernatural Paper Lunch Sack',
    id: 'GGOEGBRD128399',
    category: 'eco',
    position: '11',
  },
  {
    item_name: 'Supernatural Paper Tote',
    item_id: 'GGOEGBJD128499',
    price: '28.00',
    item_category: 'eco',
    index: 12,
    name: 'Supernatural Paper Tote',
    id: 'GGOEGBJD128499',
    category: 'eco',
    position: '12',
  },
  {
    item_name: 'Google Cambridge Campus Lapel Pin',
    item_id: 'GGOEGCBR133299',
    price: '6.00',
    item_category: 'campus',
    index: 1,
    name: 'Google Cambridge Campus Lapel Pin',
    id: 'GGOEGCBR133299',
    category: 'campus',
    position: '1',
  },
  {
    item_name: 'Google Cambridge Campus Mug',
    item_id: 'GGOEGDWR133399',
    price: '12.00',
    item_category: 'campus',
    index: 2,
    name: 'Google Cambridge Campus Mug',
    id: 'GGOEGDWR133399',
    category: 'campus',
    position: '2',
  },
  {
    item_name: 'Google Cambridge Campus Bottle',
    item_id: 'GGOEGDHJ133499',
    price: '20.00',
    item_category: 'campus',
    index: 3,
    name: 'Google Cambridge Campus Bottle',
    id: 'GGOEGDHJ133499',
    category: 'campus',
    position: '3',
  },
  {
    item_name: 'Google Cambridge Campus Tote',
    item_id: 'GGOEGBJD133999',
    price: '11.00',
    item_category: 'campus',
    index: 5,
    name: 'Google Cambridge Campus Tote',
    id: 'GGOEGBJD133999',
    category: 'campus',
    position: '5',
  },
  {
    item_name: 'Google Cambridge Campus Unisex Tee',
    item_id: 'GGOEGXXX1335',
    price: '25.00',
    item_category: 'campus',
    index: 6,
    name: 'Google Cambridge Campus Unisex Tee',
    id: 'GGOEGXXX1335',
    category: 'campus',
    position: '6',
  },
  {
    item_name: 'Google Cambridge Campus Ladies Tee',
    item_id: 'GGOEGXXX1336',
    price: '25.00',
    item_category: 'campus',
    index: 7,
    name: 'Google Cambridge Campus Ladies Tee',
    id: 'GGOEGXXX1336',
    category: 'campus',
    position: '7',
  },
  {
    item_name: 'Google Cambridge Campus Zip Hoodie',
    item_id: 'GGOEGXXX1337',
    price: '58.00',
    item_category: 'campus',
    index: 8,
    name: 'Google Cambridge Campus Zip Hoodie',
    id: 'GGOEGXXX1337',
    category: 'campus',
    position: '8',
  },
  {
    item_name: 'Google NYC Campus Bottle',
    item_id: 'GGOEGDHJ140199',
    price: '20.00',
    item_category: 'campus',
    index: 9,
    name: 'Google NYC Campus Bottle',
    id: 'GGOEGDHJ140199',
    category: 'campus',
    position: '9',
  },
  {
    item_name: 'Google NYC Campus Unisex Tee',
    item_id: 'GGOEGXXX1402',
    price: '25.00',
    item_category: 'campus',
    index: 10,
    name: 'Google NYC Campus Unisex Tee',
    id: 'GGOEGXXX1402',
    category: 'campus',
    position: '10',
  },
  {
    item_name: 'Google NYC Campus Ladies Tee',
    item_id: 'GGOEGXXX1403',
    price: '25.00',
    item_category: 'campus',
    index: 11,
    name: 'Google NYC Campus Ladies Tee',
    id: 'GGOEGXXX1403',
    category: 'campus',
    position: '11',
  },
  {
    item_name: 'Google NYC Campus Zip Hoodie',
    item_id: 'GGOEGXXX1404',
    price: '58.00',
    item_category: 'campus',
    index: 12,
    name: 'Google NYC Campus Zip Hoodie',
    id: 'GGOEGXXX1404',
    category: 'campus',
    position: '12',
  },
  {
    item_name: '#IamRemarkable Unisex Hoodie',
    item_id: 'GGCOGXXX1008',
    price: '32.00',
    item_category: 'apparel-womens',
    index: 1,
    name: '#IamRemarkable Unisex Hoodie',
    id: 'GGCOGXXX1008',
    category: 'apparel-womens',
    position: '1',
  },
  {
    item_name: "Google Women's Microfleece Jacket Black",
    item_id: 'GGOEGXXX0963',
    price: '75.00',
    item_category: 'apparel-womens',
    index: 2,
    name: "Google Women's Microfleece Jacket Black",
    id: 'GGOEGXXX0963',
    category: 'apparel-womens',
    position: '2',
  },
  {
    item_name: "Google Women's Grid Zip-Up",
    item_id: 'GGOEGXXX1078',
    price: '63.00',
    item_category: 'apparel-womens',
    index: 3,
    name: "Google Women's Grid Zip-Up",
    id: 'GGOEGXXX1078',
    category: 'apparel-womens',
    position: '3',
  },
  {
    item_name: "Google Women's Striped L/S",
    item_id: 'GGOEGXXX1181',
    price: '29.00',
    item_category: 'apparel-womens',
    index: 4,
    name: "Google Women's Striped L/S",
    id: 'GGOEGXXX1181',
    category: 'apparel-womens',
    position: '4',
  },
  {
    item_name: "Google Women's Puff Jacket Black",
    item_id: 'GGOEGXXX1384',
    price: '115.00',
    item_category: 'apparel-womens',
    index: 5,
    name: "Google Women's Puff Jacket Black",
    id: 'GGOEGXXX1384',
    category: 'apparel-womens',
    position: '5',
  },
  {
    item_name: 'Google Campus Bike Eco Tee Navy',
    item_id: 'GGOEGXXX1193',
    price: '25.00',
    item_category: 'apparel-womens',
    index: 6,
    name: 'Google Campus Bike Eco Tee Navy',
    id: 'GGOEGXXX1193',
    category: 'apparel-womens',
    position: '6',
  },
  {
    item_name: 'Google Heather Green Speckled Tee',
    item_id: 'GGOEGXXX1343',
    price: '30.00',
    item_category: 'apparel-womens',
    index: 7,
    name: 'Google Heather Green Speckled Tee',
    id: 'GGOEGXXX1343',
    category: 'apparel-womens',
    position: '7',
  },
  {
    item_name: 'Google Navy Speckled Tee',
    item_id: 'GGOEGXXX1344',
    price: '30.00',
    item_category: 'apparel-womens',
    index: 8,
    name: 'Google Navy Speckled Tee',
    id: 'GGOEGXXX1344',
    category: 'apparel-womens',
    position: '8',
  },
  {
    item_name: 'Google Beekeepers Tee Mint',
    item_id: 'GGOEGXXX1265',
    price: '25.00',
    item_category: 'apparel-womens',
    index: 9,
    name: 'Google Beekeepers Tee Mint',
    id: 'GGOEGXXX1265',
    category: 'apparel-womens',
    position: '9',
  },
  {
    item_name: 'Stan and Friends Tee Green',
    item_id: 'GGOEGXXX1267',
    price: '25.00',
    item_category: 'apparel-womens',
    index: 10,
    name: 'Stan and Friends Tee Green',
    id: 'GGOEGXXX1267',
    category: 'apparel-womens',
    position: '10',
  },
  {
    item_name: 'Android Garden Tee Orange',
    item_id: 'GGOEGXXX1264',
    price: '29.00',
    item_category: 'apparel-womens',
    index: 11,
    name: 'Android Garden Tee Orange',
    id: 'GGOEGXXX1264',
    category: 'apparel-womens',
    position: '11',
  },
  {
    item_name: '#IamRemarkable Ladies T-Shirt',
    item_id: 'GGCOGXXX1007',
    price: '12.00',
    item_category: 'apparel-womens',
    index: 12,
    name: '#IamRemarkable Ladies T-Shirt',
    id: 'GGCOGXXX1007',
    category: 'apparel-womens',
    position: '12',
  },
  {
    item_name: 'Google Crew Striped Athletic Sock',
    item_id: 'GGOEGAXA123510',
    price: '17.00',
    item_category: 'apparel-socks',
    index: 2,
    name: 'Google Crew Striped Athletic Sock',
    id: 'GGOEGAXA123510',
    category: 'apparel-socks',
    position: '2',
  },
  {
    item_name: 'Google Crew Combed Cotton Sock',
    item_id: 'GGOEGAXA123610',
    price: '17.00',
    item_category: 'apparel-socks',
    index: 3,
    name: 'Google Crew Combed Cotton Sock',
    id: 'GGOEGAXA123610',
    category: 'apparel-socks',
    position: '3',
  },
  {
    item_name: 'Android Iconic Socks',
    item_id: 'GGOEAAKQ137410',
    price: '17.00',
    item_category: 'apparel-socks',
    index: 4,
    name: 'Android Iconic Socks',
    id: 'GGOEAAKQ137410',
    category: 'apparel-socks',
    position: '4',
  },
  {
    item_name: 'Google Packable Bag Black',
    item_id: 'GGOEGBJB099799',
    price: '20.00',
    item_category: 'lifestyle-bags',
    index: 1,
    name: 'Google Packable Bag Black',
    id: 'GGOEGBJB099799',
    category: 'lifestyle-bags',
    position: '1',
  },
  {
    item_name: 'Google Mesh Bag Blue',
    item_id: 'GGOEGBJC100199',
    price: '6.00',
    item_category: 'lifestyle-bags',
    index: 2,
    name: 'Google Mesh Bag Blue',
    id: 'GGOEGBJC100199',
    category: 'lifestyle-bags',
    position: '2',
  },
  {
    item_name: 'Google Flat Front Bag Grey',
    item_id: 'GGOEGBJJ099699',
    price: '30.00',
    item_category: 'lifestyle-bags',
    index: 3,
    name: 'Google Flat Front Bag Grey',
    id: 'GGOEGBJJ099699',
    category: 'lifestyle-bags',
    position: '3',
  },
  {
    item_name: 'Google Utility Bag Grey',
    item_id: 'GGOEGBJJ099499',
    price: '10.00',
    item_category: 'lifestyle-bags',
    index: 4,
    name: 'Google Utility Bag Grey',
    id: 'GGOEGBJJ099499',
    category: 'lifestyle-bags',
    position: '4',
  },
  {
    item_name: 'Google Confetti Accessory Pouch',
    item_id: 'GGOEGBBD122099',
    price: '12.00',
    item_category: 'lifestyle-bags',
    index: 5,
    name: 'Google Confetti Accessory Pouch',
    id: 'GGOEGBBD122099',
    category: 'lifestyle-bags',
    position: '5',
  },
  {
    item_name: 'Google Campus Bike Tote Navy',
    item_id: 'GGOEGBJC122399',
    price: '11.00',
    item_category: 'lifestyle-bags',
    index: 6,
    name: 'Google Campus Bike Tote Navy',
    id: 'GGOEGBJC122399',
    category: 'lifestyle-bags',
    position: '6',
  },
  {
    item_name: 'Google Laptop Sleeve Charcoal',
    item_id: 'GGOEGABJ099599',
    price: '20.00',
    item_category: 'lifestyle-bags',
    index: 7,
    name: 'Google Laptop Sleeve Charcoal',
    id: 'GGOEGABJ099599',
    category: 'lifestyle-bags',
    position: '7',
  },
  {
    item_name: 'Google Incognito Messenger Bag',
    item_id: 'GGOEGBJJ103799',
    price: '75.00',
    item_category: 'lifestyle-bags',
    index: 8,
    name: 'Google Incognito Messenger Bag',
    id: 'GGOEGBJJ103799',
    category: 'lifestyle-bags',
    position: '8',
  },
  {
    item_name: 'Google Utility BackPack',
    item_id: 'GGOEGBRJ114199',
    price: '120.00',
    item_category: 'lifestyle-bags',
    index: 9,
    name: 'Google Utility BackPack',
    id: 'GGOEGBRJ114199',
    category: 'lifestyle-bags',
    position: '9',
  },
  {
    item_name: 'Google Large Tote White',
    item_id: 'GGOEGBJQ125099',
    price: '13.00',
    item_category: 'lifestyle-bags',
    index: 10,
    name: 'Google Large Tote White',
    id: 'GGOEGBJQ125099',
    category: 'lifestyle-bags',
    position: '10',
  },
  {
    item_name: 'Google Mesh Bag Red',
    item_id: 'GGOEGBJR100099',
    price: '6.00',
    item_category: 'lifestyle-bags',
    index: 11,
    name: 'Google Mesh Bag Red',
    id: 'GGOEGBJR100099',
    category: 'lifestyle-bags',
    position: '11',
  },
  {
    item_name: 'Google Incognito Dopp Kit V2',
    item_id: 'GGOEGBRC128299',
    price: '48.00',
    item_category: 'lifestyle-bags',
    index: 12,
    name: 'Google Incognito Dopp Kit V2',
    id: 'GGOEGBRC128299',
    category: 'lifestyle-bags',
    position: '12',
  },
  {
    item_name: 'Android Buoy Bottle',
    item_id: 'GGOEADHH117199',
    price: '8.00',
    item_category: 'lifestyle-drinkware',
    index: 1,
    name: 'Android Buoy Bottle',
    id: 'GGOEADHH117199',
    category: 'lifestyle-drinkware',
    position: '1',
  },
  {
    item_name: 'Google Campus Bike Bottle',
    item_id: 'GGOEGDHL116999',
    price: '27.00',
    item_category: 'lifestyle-drinkware',
    index: 2,
    name: 'Google Campus Bike Bottle',
    id: 'GGOEGDHL116999',
    category: 'lifestyle-drinkware',
    position: '2',
  },
  {
    item_name: 'Google Cup Cap Tumbler Grey',
    item_id: 'GGOEGDHJ136799',
    price: '30.00',
    item_category: 'lifestyle-drinkware',
    index: 3,
    name: 'Google Cup Cap Tumbler Grey',
    id: 'GGOEGDHJ136799',
    category: 'lifestyle-drinkware',
    position: '3',
  },
  {
    item_name: 'Android Iconic Bottle Black',
    item_id: 'GGOEADHB129299',
    price: '24.00',
    item_category: 'lifestyle-drinkware',
    index: 4,
    name: 'Android Iconic Bottle Black',
    id: 'GGOEADHB129299',
    category: 'lifestyle-drinkware',
    position: '4',
  },
  {
    item_name: 'Android Iconic Glass Bottle Green',
    item_id: 'GGOEADHH129499',
    price: '24.00',
    item_category: 'lifestyle-drinkware',
    index: 5,
    name: 'Android Iconic Glass Bottle Green',
    id: 'GGOEADHH129499',
    category: 'lifestyle-drinkware',
    position: '5',
  },
  {
    item_name: '#IamRemarkable Water Bottle',
    item_id: 'GGCOGDHC101099',
    price: '15.00',
    item_category: 'lifestyle-drinkware',
    index: 6,
    name: '#IamRemarkable Water Bottle',
    id: 'GGCOGDHC101099',
    category: 'lifestyle-drinkware',
    position: '6',
  },
  {
    item_name: 'Stainless Bent Straw/Cleaner',
    item_id: 'GGOEGDBJ132299',
    price: '3.50',
    item_category: 'lifestyle-drinkware',
    index: 7,
    name: 'Stainless Bent Straw/Cleaner',
    id: 'GGOEGDBJ132299',
    category: 'lifestyle-drinkware',
    position: '7',
  },
  {
    item_name: 'Stainless Straight Straw/Cleaner',
    item_id: 'GGOEGDBJ132399',
    price: '3.50',
    item_category: 'lifestyle-drinkware',
    index: 8,
    name: 'Stainless Straight Straw/Cleaner',
    id: 'GGOEGDBJ132399',
    category: 'lifestyle-drinkware',
    position: '8',
  },
  {
    item_name: 'Google KeepCup',
    item_id: 'GGOEGDHG133099',
    price: '35.00',
    item_category: 'lifestyle-drinkware',
    index: 9,
    name: 'Google KeepCup',
    id: 'GGOEGDHG133099',
    category: 'lifestyle-drinkware',
    position: '9',
  },
  {
    item_name: 'Google 24 oz Ring Bottle Red',
    item_id: 'GGOEGDHR098199',
    price: '7.00',
    item_category: 'lifestyle-drinkware',
    index: 10,
    name: 'Google 24 oz Ring Bottle Red',
    id: 'GGOEGDHR098199',
    category: 'lifestyle-drinkware',
    position: '10',
  },
  {
    item_name: 'Google Campus Bike Corkbase Mug Blue',
    item_id: 'GGOEGDWC122799',
    price: '17.00',
    item_category: 'lifestyle-drinkware',
    index: 11,
    name: 'Google Campus Bike Corkbase Mug Blue',
    id: 'GGOEGDWC122799',
    category: 'lifestyle-drinkware',
    position: '11',
  },
  {
    item_name: 'Google Camp Mug Ivory',
    item_id: 'GGOEGDWD108799',
    price: '13.00',
    item_category: 'lifestyle-drinkware',
    index: 12,
    name: 'Google Camp Mug Ivory',
    id: 'GGOEGDWD108799',
    category: 'lifestyle-drinkware',
    position: '12',
  },
  {
    item_name: 'Google Bear Baby Blanket Beige',
    item_id: 'GGCOGCBD162999',
    price: '24.00',
    item_category: 'lifestyle-small',
    index: 1,
    name: 'Google Bear Baby Blanket Beige',
    id: 'GGCOGCBD162999',
    category: 'lifestyle-small',
    position: '1',
  },
  {
    item_name: 'Google LoveHandle Black',
    item_id: 'GGOEGABB137799',
    price: '10.00',
    item_category: 'lifestyle-small',
    index: 2,
    name: 'Google LoveHandle Black',
    id: 'GGOEGABB137799',
    category: 'lifestyle-small',
    position: '2',
  },
  {
    item_name: 'Google Laptop Sleeve Charcoal',
    item_id: 'GGOEGABJ099599',
    price: '20.00',
    item_category: 'lifestyle-small',
    index: 3,
    name: 'Google Laptop Sleeve Charcoal',
    id: 'GGOEGABJ099599',
    category: 'lifestyle-small',
    position: '3',
  },
  {
    item_name: 'Google Phone Stand Bamboo',
    item_id: 'GGOEGABK101099',
    price: '5.00',
    item_category: 'lifestyle-small',
    index: 4,
    name: 'Google Phone Stand Bamboo',
    id: 'GGOEGABK101099',
    category: 'lifestyle-small',
    position: '4',
  },
  {
    item_name: 'Google Mouse Pad Navy',
    item_id: 'GGOEGABL100799',
    price: '5.00',
    item_category: 'lifestyle-small',
    index: 5,
    name: 'Google Mouse Pad Navy',
    id: 'GGOEGABL100799',
    category: 'lifestyle-small',
    position: '5',
  },
  {
    item_name: 'Google Tech Taco',
    item_id: 'GGOEGBGJ132699',
    price: '4.00',
    item_category: 'lifestyle-small',
    index: 6,
    name: 'Google Tech Taco',
    id: 'GGOEGBGJ132699',
    category: 'lifestyle-small',
    position: '6',
  },
  {
    item_name: 'Google Utility Bag Grey',
    item_id: 'GGOEGBJJ099499',
    price: '10.00',
    item_category: 'lifestyle-small',
    index: 7,
    name: 'Google Utility Bag Grey',
    id: 'GGOEGBJJ099499',
    category: 'lifestyle-small',
    position: '7',
  },
  {
    item_name: 'Google Small Cable Organizer Blue',
    item_id: 'GGOEGEGC099099',
    price: '3.00',
    item_category: 'lifestyle-small',
    index: 8,
    name: 'Google Small Cable Organizer Blue',
    id: 'GGOEGEGC099099',
    category: 'lifestyle-small',
    position: '8',
  },
  {
    item_name: 'Noogler Android Figure',
    item_id: 'GGOEACBA116699',
    price: '16.00',
    item_category: 'lifestyle-small',
    index: 9,
    name: 'Noogler Android Figure',
    id: 'GGOEACBA116699',
    category: 'lifestyle-small',
    position: '9',
  },
  {
    item_name: 'Android Iconic Pin',
    item_id: 'GGOEACBA129599',
    price: '4.00',
    item_category: 'lifestyle-small',
    index: 10,
    name: 'Android Iconic Pin',
    id: 'GGOEACBA129599',
    category: 'lifestyle-small',
    position: '10',
  },
  {
    item_name: 'Candy Cane Android Cardboard Sculpture',
    item_id: 'GGOEAFBA115299',
    price: '20.00',
    item_category: 'lifestyle-small',
    index: 11,
    name: 'Candy Cane Android Cardboard Sculpture',
    id: 'GGOEAFBA115299',
    category: 'lifestyle-small',
    position: '11',
  },
  {
    item_name: 'Snowflake Android Cardboard Sculpture',
    item_id: 'GGOEAFBA115399',
    price: '20.00',
    item_category: 'lifestyle-small',
    index: 12,
    name: 'Snowflake Android Cardboard Sculpture',
    id: 'GGOEAFBA115399',
    category: 'lifestyle-small',
    position: '12',
  },
  {
    item_name: 'Google Metallic Notebook Set',
    item_id: 'GGOEGOLC014299',
    price: '6.00',
    item_category: 'stationery-notebooks',
    index: 1,
    name: 'Google Metallic Notebook Set',
    id: 'GGOEGOLC014299',
    category: 'stationery-notebooks',
    position: '1',
  },
  {
    item_name: 'Google Small Standard Journal Navy',
    item_id: 'GGOEGOCL092999',
    price: '13.00',
    item_category: 'stationery-notebooks',
    index: 2,
    name: 'Google Small Standard Journal Navy',
    id: 'GGOEGOCL092999',
    category: 'stationery-notebooks',
    position: '2',
  },
  {
    item_name: 'Android Jotter Task Pad',
    item_id: 'GGOEAOLC152099',
    price: '3.00',
    item_category: 'stationery-notebooks',
    index: 3,
    name: 'Android Jotter Task Pad',
    id: 'GGOEAOLC152099',
    category: 'stationery-notebooks',
    position: '3',
  },
  {
    item_name: 'Google Land & Sea Journal Set',
    item_id: 'GGCOGOCA157331',
    price: '15.00',
    item_category: 'stationery-notebooks',
    index: 4,
    name: 'Google Land & Sea Journal Set',
    id: 'GGCOGOCA157331',
    category: 'stationery-notebooks',
    position: '4',
  },
  {
    item_name: 'Google Color Block Notebook',
    item_id: 'GGOEGOCA121499',
    price: '12.00',
    item_category: 'stationery-notebooks',
    index: 5,
    name: 'Google Color Block Notebook',
    id: 'GGOEGOCA121499',
    category: 'stationery-notebooks',
    position: '5',
  },
  {
    item_name: '#IamRemarkable Journal',
    item_id: 'GGCOGOCC101199',
    price: '8.00',
    item_category: 'stationery-notebooks',
    index: 6,
    name: '#IamRemarkable Journal',
    id: 'GGCOGOCC101199',
    category: 'stationery-notebooks',
    position: '6',
  },
  {
    item_name: 'Google Large Standard Journal Grey',
    item_id: 'GGOEGOCJ093999',
    price: '16.00',
    item_category: 'stationery-notebooks',
    index: 7,
    name: 'Google Large Standard Journal Grey',
    id: 'GGOEGOCJ093999',
    category: 'stationery-notebooks',
    position: '7',
  },
  {
    item_name: 'Google Black Cork Journal',
    item_id: 'GGOEGOCB131799',
    price: '12.00',
    item_category: 'stationery-notebooks',
    index: 8,
    name: 'Google Black Cork Journal',
    id: 'GGOEGOCB131799',
    category: 'stationery-notebooks',
    position: '8',
  },
  {
    item_name: 'Google Cloud Journal',
    item_id: 'GGOECOLJ164299',
    price: '18.00',
    item_category: 'stationery-notebooks',
    index: 9,
    name: 'Google Cloud Journal',
    id: 'GGOECOLJ164299',
    category: 'stationery-notebooks',
    position: '9',
  },
  {
    item_name: 'Android Large Trace Journal Black',
    item_id: 'GGOEAOCB092799',
    price: '16.00',
    item_category: 'stationery-notebooks',
    index: 10,
    name: 'Android Large Trace Journal Black',
    id: 'GGOEAOCB092799',
    category: 'stationery-notebooks',
    position: '10',
  },
  {
    item_name: 'Google Mural Sticky Note Pad',
    item_id: 'GGOEGOLA127499',
    price: '20.00',
    item_category: 'stationery-notebooks',
    index: 11,
    name: 'Google Mural Sticky Note Pad',
    id: 'GGOEGOLA127499',
    category: 'stationery-notebooks',
    position: '11',
  },
  {
    item_name: 'Android Flex Journal White',
    item_id: 'GGOEAOCQ100399',
    price: '8.00',
    item_category: 'stationery-notebooks',
    index: 12,
    name: 'Android Flex Journal White',
    id: 'GGOEAOCQ100399',
    category: 'stationery-notebooks',
    position: '12',
  },
  {
    item_name: 'Google Laptop and Cell Phone Stickers',
    item_id: 'GGOEGFKQ020399',
    price: '3.00',
    item_category: 'stationery-stickers',
    index: 1,
    name: 'Google Laptop and Cell Phone Stickers',
    id: 'GGOEGFKQ020399',
    category: 'stationery-stickers',
    position: '1',
  },
  {
    item_name: 'Keyboard DOT Sticker',
    item_id: 'GGOEGFKA022299',
    price: '2.00',
    item_category: 'stationery-stickers',
    index: 2,
    name: 'Keyboard DOT Sticker',
    id: 'GGOEGFKA022299',
    category: 'stationery-stickers',
    position: '2',
  },
  {
    item_name: 'Google Mural Sticker Sheet',
    item_id: 'GGOEGAKA126399',
    price: '3.00',
    item_category: 'stationery-stickers',
    index: 3,
    name: 'Google Mural Sticker Sheet',
    id: 'GGOEGAKA126399',
    category: 'stationery-stickers',
    position: '3',
  },
  {
    item_name: 'Android SM S/F18 Sticker Sheet',
    item_id: 'GGOEACBA104599',
    price: '3.00',
    item_category: 'stationery-stickers',
    index: 4,
    name: 'Android SM S/F18 Sticker Sheet',
    id: 'GGOEACBA104599',
    category: 'stationery-stickers',
    position: '4',
  },
  {
    item_name: 'Android Large Removable Sticker Sheet',
    item_id: 'GGOEAFKA087599',
    price: '3.00',
    item_category: 'stationery-stickers',
    index: 5,
    name: 'Android Large Removable Sticker Sheet',
    id: 'GGOEAFKA087599',
    category: 'stationery-stickers',
    position: '5',
  },
  {
    item_name: 'Android Iconic 4&quot; Decal',
    item_id: 'GGOEAFKQ130599',
    price: '1.50',
    item_category: 'stationery-stickers',
    index: 6,
    name: 'Android Iconic 4&quot; Decal',
    id: 'GGOEAFKQ130599',
    category: 'stationery-stickers',
    position: '6',
  },
  {
    item_name: 'Google Emoji Sticker Pack',
    item_id: 'GGOEGFKA086699',
    price: '5.00',
    item_category: 'stationery-stickers',
    index: 7,
    name: 'Google Emoji Sticker Pack',
    id: 'GGOEGFKA086699',
    category: 'stationery-stickers',
    position: '7',
  },
  {
    item_name: 'Android Iconic Sticker Sheet',
    item_id: 'GGOEAFKQ130699',
    price: '3.00',
    item_category: 'stationery-stickers',
    index: 8,
    name: 'Android Iconic Sticker Sheet',
    id: 'GGOEAFKQ130699',
    category: 'stationery-stickers',
    position: '8',
  },
  {
    item_name: '#IamRemarkable Pen',
    item_id: 'GGCOGOAC101259',
    price: '1.75',
    item_category: 'stationery-writing',
    index: 1,
    name: '#IamRemarkable Pen',
    id: 'GGCOGOAC101259',
    category: 'stationery-writing',
    position: '1',
  },
  {
    item_name: 'Google Light Pen Blue',
    item_id: 'GGOEGOAC089999',
    price: '3.00',
    item_category: 'stationery-writing',
    index: 2,
    name: 'Google Light Pen Blue',
    id: 'GGOEGOAC089999',
    category: 'stationery-writing',
    position: '2',
  },
  {
    item_name: 'Google Light Pen Red',
    item_id: 'GGOEGOAR090099',
    price: '3.00',
    item_category: 'stationery-writing',
    index: 3,
    name: 'Google Light Pen Red',
    id: 'GGOEGOAR090099',
    category: 'stationery-writing',
    position: '3',
  },
  {
    item_name: 'Google Light Pen Green',
    item_id: 'GGOEGOAH090199',
    price: '3.00',
    item_category: 'stationery-writing',
    index: 4,
    name: 'Google Light Pen Green',
    id: 'GGOEGOAH090199',
    category: 'stationery-writing',
    position: '4',
  },
  {
    item_name: 'Google Light Pen Yellow',
    item_id: 'GGOEGOAT090299',
    price: '3.00',
    item_category: 'stationery-writing',
    index: 5,
    name: 'Google Light Pen Yellow',
    id: 'GGOEGOAT090299',
    category: 'stationery-writing',
    position: '5',
  },
  {
    item_name: 'Google Pen Grey',
    item_id: 'GGOEGOAJ101399',
    price: '1.75',
    item_category: 'stationery-writing',
    index: 6,
    name: 'Google Pen Grey',
    id: 'GGOEGOAJ101399',
    category: 'stationery-writing',
    position: '6',
  },
  {
    item_name: 'Google Pen White',
    item_id: 'GGOEGOAQ101299',
    price: '1.75',
    item_category: 'stationery-writing',
    index: 7,
    name: 'Google Pen White',
    id: 'GGOEGOAQ101299',
    category: 'stationery-writing',
    position: '7',
  },
  {
    item_name: 'Google Pen Bright Blue',
    item_id: 'GGOEGOAC123799',
    price: '1.75',
    item_category: 'stationery-writing',
    index: 8,
    name: 'Google Pen Bright Blue',
    id: 'GGOEGOAC123799',
    category: 'stationery-writing',
    position: '8',
  },
  {
    item_name: 'Google Pen Grass Green',
    item_id: 'GGOEGOAH124099',
    price: '1.75',
    item_category: 'stationery-writing',
    index: 9,
    name: 'Google Pen Grass Green',
    id: 'GGOEGOAH124099',
    category: 'stationery-writing',
    position: '9',
  },
  {
    item_name: 'Google Pen Citron',
    item_id: 'GGOEGOAH124199',
    price: '1.75',
    item_category: 'stationery-writing',
    index: 10,
    name: 'Google Pen Citron',
    id: 'GGOEGOAH124199',
    category: 'stationery-writing',
    position: '10',
  },
  {
    item_name: 'Google Pen Neon Coral',
    item_id: 'GGOEGOAN123899',
    price: '1.75',
    item_category: 'stationery-writing',
    index: 11,
    name: 'Google Pen Neon Coral',
    id: 'GGOEGOAN123899',
    category: 'stationery-writing',
    position: '11',
  },
  {
    item_name: 'Google Pen Lilac',
    item_id: 'GGOEGOAP123999',
    price: '1.75',
    item_category: 'stationery-writing',
    index: 12,
    name: 'Google Pen Lilac',
    id: 'GGOEGOAP123999',
    category: 'stationery-writing',
    position: '12',
  },
  {
    item_name: 'Android Jotter Task Pad',
    item_id: 'GGOEAOLC152099',
    price: '3.00',
    item_category: 'brand-android',
    index: 1,
    name: 'Android Jotter Task Pad',
    id: 'GGOEAOLC152099',
    category: 'brand-android',
    position: '1',
  },
  {
    item_name: 'Android Buoy Bottle',
    item_id: 'GGOEADHH117199',
    price: '8.00',
    item_category: 'brand-android',
    index: 2,
    name: 'Android Buoy Bottle',
    id: 'GGOEADHH117199',
    category: 'brand-android',
    position: '2',
  },
  {
    item_name: 'Android SM S/F18 Sticker Sheet',
    item_id: 'GGOEACBA104599',
    price: '3.00',
    item_category: 'brand-android',
    index: 3,
    name: 'Android SM S/F18 Sticker Sheet',
    id: 'GGOEACBA104599',
    category: 'brand-android',
    position: '3',
  },
  {
    item_name: 'Android Large Removable Sticker Sheet',
    item_id: 'GGOEAFKA087599',
    price: '3.00',
    item_category: 'brand-android',
    index: 4,
    name: 'Android Large Removable Sticker Sheet',
    id: 'GGOEAFKA087599',
    category: 'brand-android',
    position: '4',
  },
  {
    item_name: 'Noogler Android Figure',
    item_id: 'GGOEACBA116699',
    price: '16.00',
    item_category: 'brand-android',
    index: 5,
    name: 'Noogler Android Figure',
    id: 'GGOEACBA116699',
    category: 'brand-android',
    position: '5',
  },
  {
    item_name: 'Android Iconic Hat Green',
    item_id: 'GGOEAHPL130910',
    price: '16.00',
    item_category: 'brand-android',
    index: 6,
    name: 'Android Iconic Hat Green',
    id: 'GGOEAHPL130910',
    category: 'brand-android',
    position: '6',
  },
  {
    item_name: 'Android Techie 3D Framed Art',
    item_id: 'GGOEAFBA115499',
    price: '40.00',
    item_category: 'brand-android',
    index: 7,
    name: 'Android Techie 3D Framed Art',
    id: 'GGOEAFBA115499',
    category: 'brand-android',
    position: '7',
  },
  {
    item_name: 'Android Large Trace Journal Black',
    item_id: 'GGOEAOCB092799',
    price: '16.00',
    item_category: 'brand-android',
    index: 8,
    name: 'Android Large Trace Journal Black',
    id: 'GGOEAOCB092799',
    category: 'brand-android',
    position: '8',
  },
  {
    item_name: 'Android Super Hero 3D Framed Art',
    item_id: 'GGOEAFBA115599',
    price: '40.00',
    item_category: 'brand-android',
    index: 9,
    name: 'Android Super Hero 3D Framed Art',
    id: 'GGOEAFBA115599',
    category: 'brand-android',
    position: '9',
  },
  {
    item_name: 'Android Iconic Pen',
    item_id: 'GGOEAOAL129199',
    price: '1.75',
    item_category: 'brand-android',
    index: 10,
    name: 'Android Iconic Pen',
    id: 'GGOEAOAL129199',
    category: 'brand-android',
    position: '10',
  },
  {
    item_name: 'Android Hipster Pin',
    item_id: 'GGOEACBA104999',
    price: '8.00',
    item_category: 'brand-android',
    index: 11,
    name: 'Android Hipster Pin',
    id: 'GGOEACBA104999',
    category: 'brand-android',
    position: '11',
  },
  {
    item_name: 'Android Pocket Youth Tee Green',
    item_id: 'GGOEAXXX1302',
    price: '25.00',
    item_category: 'brand-android',
    index: 12,
    name: 'Android Pocket Youth Tee Green',
    id: 'GGOEAXXX1302',
    category: 'brand-android',
    position: '12',
  },
  {
    item_name: 'Google Bear Baby Blanket Beige',
    item_id: 'GGCOGCBD162999',
    price: '24.00',
    item_category: 'brand-google',
    index: 1,
    name: 'Google Bear Baby Blanket Beige',
    id: 'GGCOGCBD162999',
    category: 'brand-google',
    position: '1',
  },
  {
    item_name: 'Google Bot (Multicolored)',
    item_id: 'GGOEGEBA164399',
    price: '10.00',
    item_category: 'brand-google',
    index: 2,
    name: 'Google Bot (Multicolored)',
    id: 'GGOEGEBA164399',
    category: 'brand-google',
    position: '2',
  },
  {
    item_name: 'Google Cloud Journal',
    item_id: 'GGOECOLJ164299',
    price: '18.00',
    item_category: 'brand-google',
    index: 3,
    name: 'Google Cloud Journal',
    id: 'GGOECOLJ164299',
    category: 'brand-google',
    position: '3',
  },
  {
    item_name: 'White Google Cloud Tumbler',
    item_id: 'GGOECDNQ163899',
    price: '27.00',
    item_category: 'brand-google',
    index: 4,
    name: 'White Google Cloud Tumbler',
    id: 'GGOECDNQ163899',
    category: 'brand-google',
    position: '4',
  },
  {
    item_name: 'Google Shoreline Water Bottle',
    item_id: 'GGOECDHQ163999',
    price: '26.00',
    item_category: 'brand-google',
    index: 5,
    name: 'Google Shoreline Water Bottle',
    id: 'GGOECDHQ163999',
    category: 'brand-google',
    position: '5',
  },
  {
    item_name: 'Google Cloud Pen',
    item_id: 'GGOECOAQ163799',
    price: '3.00',
    item_category: 'brand-google',
    index: 6,
    name: 'Google Cloud Pen',
    id: 'GGOECOAQ163799',
    category: 'brand-google',
    position: '6',
  },
  {
    item_name: 'Google Chrome Dino Light Up Water Bottle',
    item_id: 'GGOEGDHB163199',
    price: '24.00',
    item_category: 'brand-google',
    index: 7,
    name: 'Google Chrome Dino Light Up Water Bottle',
    id: 'GGOEGDHB163199',
    category: 'brand-google',
    position: '7',
  },
  {
    item_name: 'Google Navy Polo',
    item_id: 'GGOEGXXX1632',
    price: '48.00',
    item_category: 'brand-google',
    index: 8,
    name: 'Google Navy Polo',
    id: 'GGOEGXXX1632',
    category: 'brand-google',
    position: '8',
  },
  {
    item_name: 'Google Charcoal Unisex Badge Tee',
    item_id: 'GGOEGXXX1633',
    price: '21.00',
    item_category: 'brand-google',
    index: 9,
    name: 'Google Charcoal Unisex Badge Tee',
    id: 'GGOEGXXX1633',
    category: 'brand-google',
    position: '9',
  },
  {
    item_name: 'Google Cloud Polo',
    item_id: 'GGOECXXX1635',
    price: '46.00',
    item_category: 'brand-google',
    index: 10,
    name: 'Google Cloud Polo',
    id: 'GGOECXXX1635',
    category: 'brand-google',
    position: '10',
  },
  {
    item_name: 'Google Cloud Unisex Tee',
    item_id: 'GGOECXXX1636',
    price: '28.00',
    item_category: 'brand-google',
    index: 11,
    name: 'Google Cloud Unisex Tee',
    id: 'GGOECXXX1636',
    category: 'brand-google',
    position: '11',
  },
  {
    item_name: 'Google Aluminum Bottle Red',
    item_id: 'GGOEGDHR162799',
    price: '8.00',
    item_category: 'brand-google',
    index: 12,
    name: 'Google Aluminum Bottle Red',
    id: 'GGOEGDHR162799',
    category: 'brand-google',
    position: '12',
  },
  {
    item_name: 'Google Cloud Tumbler 20oz',
    item_id: 'GGOECDNQ165699',
    price: '29.00',
    item_category: 'brand-cloud',
    index: 1,
    name: 'Google Cloud Tumbler 20oz',
    id: 'GGOECDNQ165699',
    category: 'brand-cloud',
    position: '1',
  },
  {
    item_name: 'Google Cloud Unisex Tri-Blend Crew Tee',
    item_id: 'GGOECXXX1655',
    price: '30.00',
    item_category: 'brand-cloud',
    index: 2,
    name: 'Google Cloud Unisex Tri-Blend Crew Tee',
    id: 'GGOECXXX1655',
    category: 'brand-cloud',
    position: '2',
  },
  {
    item_name: 'Google Cloud Unisex Carhartt Crew Sweatshirt',
    item_id: 'GGOECXXX1654',
    price: '69.00',
    item_category: 'brand-cloud',
    index: 3,
    name: 'Google Cloud Unisex Carhartt Crew Sweatshirt',
    id: 'GGOECXXX1654',
    category: 'brand-cloud',
    position: '3',
  },
  {
    item_name: 'Google Cloud Journal',
    item_id: 'GGOECOLJ164299',
    price: '18.00',
    item_category: 'brand-cloud',
    index: 4,
    name: 'Google Cloud Journal',
    id: 'GGOECOLJ164299',
    category: 'brand-cloud',
    position: '4',
  },
  {
    item_name: 'White Google Cloud Tumbler',
    item_id: 'GGOECDNQ163899',
    price: '27.00',
    item_category: 'brand-cloud',
    index: 5,
    name: 'White Google Cloud Tumbler',
    id: 'GGOECDNQ163899',
    category: 'brand-cloud',
    position: '5',
  },
  {
    item_name: 'Google Cloud Pen',
    item_id: 'GGOECOAQ163799',
    price: '3.00',
    item_category: 'brand-cloud',
    index: 6,
    name: 'Google Cloud Pen',
    id: 'GGOECOAQ163799',
    category: 'brand-cloud',
    position: '6',
  },
  {
    item_name: 'Google Cloud Polo',
    item_id: 'GGOECXXX1635',
    price: '46.00',
    item_category: 'brand-cloud',
    index: 7,
    name: 'Google Cloud Polo',
    id: 'GGOECXXX1635',
    category: 'brand-cloud',
    position: '7',
  },
  {
    item_name: 'Google Cloud Unisex Tee',
    item_id: 'GGOECXXX1636',
    price: '28.00',
    item_category: 'brand-cloud',
    index: 8,
    name: 'Google Cloud Unisex Tee',
    id: 'GGOECXXX1636',
    category: 'brand-cloud',
    position: '8',
  },
  {
    item_name: 'Google Cloud  Unisex Zip Hoodie',
    item_id: 'GGOECXXX1630',
    price: '69.00',
    item_category: 'brand-cloud',
    index: 9,
    name: 'Google Cloud  Unisex Zip Hoodie',
    id: 'GGOECXXX1630',
    category: 'brand-cloud',
    position: '9',
  },
  {
    item_name: 'Google Chrome Dino Light Up Water Bottle',
    item_id: 'GGOEGDHB163199',
    price: '24.00',
    item_category: 'brand-dino',
    index: 1,
    name: 'Google Chrome Dino Light Up Water Bottle',
    id: 'GGOEGDHB163199',
    category: 'brand-dino',
    position: '1',
  },
  {
    item_name: 'Google Dino Game Tee',
    item_id: 'GGOEGXXX1194',
    price: '40.00',
    item_category: 'brand-dino',
    index: 2,
    name: 'Google Dino Game Tee',
    id: 'GGOEGXXX1194',
    category: 'brand-dino',
    position: '2',
  },
  {
    item_name: 'Google Chrome Dinosaur Collectible',
    item_id: 'GGOEGABJ125299',
    price: '30.00',
    item_category: 'brand-dino',
    index: 3,
    name: 'Google Chrome Dinosaur Collectible',
    id: 'GGOEGABJ125299',
    category: 'brand-dino',
    position: '3',
  },
  {
    item_name: 'YouTube Twill Sandwich Cap Black',
    item_id: 'GGOEYHBB102199',
    price: '13.00',
    item_category: 'brand-youtube',
    index: 1,
    name: 'YouTube Twill Sandwich Cap Black',
    id: 'GGOEYHBB102199',
    category: 'brand-youtube',
    position: '1',
  },
  {
    item_name: 'YouTube Iconic Play Pin',
    item_id: 'GGOEYCBR138999',
    price: '8.00',
    item_category: 'brand-youtube',
    index: 2,
    name: 'YouTube Iconic Play Pin',
    id: 'GGOEYCBR138999',
    category: 'brand-youtube',
    position: '2',
  },
  {
    item_name: 'YouTube Standards Zip Hoodie Black',
    item_id: 'GGOEYXXX1207',
    price: '60.00',
    item_category: 'brand-youtube',
    index: 3,
    name: 'YouTube Standards Zip Hoodie Black',
    id: 'GGOEYXXX1207',
    category: 'brand-youtube',
    position: '3',
  },
  {
    item_name: 'YouTube 25 oz Gear Cap Bottle Black',
    item_id: 'GGOEYDHB098499',
    price: '27.00',
    item_category: 'brand-youtube',
    index: 4,
    name: 'YouTube 25 oz Gear Cap Bottle Black',
    id: 'GGOEYDHB098499',
    category: 'brand-youtube',
    position: '4',
  },
  {
    item_name: 'YouTube Icon Tee Charcoal',
    item_id: 'GGOEYXXX1202',
    price: '22.00',
    item_category: 'brand-youtube',
    index: 5,
    name: 'YouTube Icon Tee Charcoal',
    id: 'GGOEYXXX1202',
    category: 'brand-youtube',
    position: '5',
  },
  {
    item_name: 'YouTube Icon Tee Grey',
    item_id: 'GGOEYXXX1203',
    price: '22.00',
    item_category: 'brand-youtube',
    index: 6,
    name: 'YouTube Icon Tee Grey',
    id: 'GGOEYXXX1203',
    category: 'brand-youtube',
    position: '6',
  },
  {
    item_name: 'YouTube Leather Strap Hat Black',
    item_id: 'GGOEYHPB121110',
    price: '17.00',
    item_category: 'brand-youtube',
    index: 7,
    name: 'YouTube Leather Strap Hat Black',
    id: 'GGOEYHPB121110',
    category: 'brand-youtube',
    position: '7',
  },
  {
    item_name: 'Google Tee Green',
    item_id: 'GGOEGXXX0906',
    price: '22.00',
    item_category: 'sale',
    index: 1,
    name: 'Google Tee Green',
    id: 'GGOEGXXX0906',
    category: 'sale',
    position: '1',
  },
  {
    item_name: 'Google Tee Yellow',
    item_id: 'GGOEGXXX0905',
    price: '22.00',
    item_category: 'sale',
    index: 2,
    name: 'Google Tee Yellow',
    id: 'GGOEGXXX0905',
    category: 'sale',
    position: '2',
  },
  {
    item_name: 'Android Techie 3D Framed Art',
    item_id: 'GGOEAFBA115499',
    price: '40.00',
    item_category: 'sale',
    index: 3,
    name: 'Android Techie 3D Framed Art',
    id: 'GGOEAFBA115499',
    category: 'sale',
    position: '3',
  },
  {
    item_name: 'Android Super Hero 3D Framed Art',
    item_id: 'GGOEAFBA115599',
    price: '40.00',
    item_category: 'sale',
    index: 4,
    name: 'Android Super Hero 3D Framed Art',
    id: 'GGOEAFBA115599',
    category: 'sale',
    position: '4',
  },
  {
    item_name: 'Android Large Trace Journal Black',
    item_id: 'GGOEAOCB092799',
    price: '16.00',
    item_category: 'sale',
    index: 5,
    name: 'Android Large Trace Journal Black',
    id: 'GGOEAOCB092799',
    category: 'sale',
    position: '5',
  },
  {
    item_name: 'Android Small Trace Journal Black',
    item_id: 'GGOEAOCB092899',
    price: '13.00',
    item_category: 'sale',
    index: 6,
    name: 'Android Small Trace Journal Black',
    id: 'GGOEAOCB092899',
    category: 'sale',
    position: '6',
  },
  {
    item_name: 'Google Small Standard Journal Navy',
    item_id: 'GGOEGOCL092999',
    price: '13.00',
    item_category: 'sale',
    index: 7,
    name: 'Google Small Standard Journal Navy',
    id: 'GGOEGOCL092999',
    category: 'sale',
    position: '7',
  },
  {
    item_name: 'Android SM S/F18 Sticker Sheet',
    item_id: 'GGOEACBA104599',
    price: '3.00',
    item_category: 'sale',
    index: 8,
    name: 'Android SM S/F18 Sticker Sheet',
    id: 'GGOEACBA104599',
    category: 'sale',
    position: '8',
  },
  {
    item_name: 'Candy Cane Android Cardboard Sculpture',
    item_id: 'GGOEAFBA115299',
    price: '20.00',
    item_category: 'sale',
    index: 9,
    name: 'Candy Cane Android Cardboard Sculpture',
    id: 'GGOEAFBA115299',
    category: 'sale',
    position: '9',
  },
  {
    item_name: 'Android Large Removable Sticker Sheet',
    item_id: 'GGOEAFKA087599',
    price: '3.00',
    item_category: 'sale',
    index: 10,
    name: 'Android Large Removable Sticker Sheet',
    id: 'GGOEAFKA087599',
    category: 'sale',
    position: '10',
  },
  {
    item_name: "Google Women's Striped L/S",
    item_id: 'GGOEGXXX1181',
    price: '29.00',
    item_category: 'sale',
    index: 11,
    name: "Google Women's Striped L/S",
    id: 'GGOEGXXX1181',
    category: 'sale',
    position: '11',
  },
  {
    item_name: 'Google Pocket Tee Grey',
    item_id: 'GGOEGXXX1175',
    price: '29.00',
    item_category: 'sale',
    index: 12,
    name: 'Google Pocket Tee Grey',
    id: 'GGOEGXXX1175',
    category: 'sale',
    position: '12',
  },
];
